default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: article_searcher_development

test:
  <<: *default
  database: article_searcher_test

production:
  <<: *default
  # database: storage/production.sqlite3
  # host: localhost
  url: <%= ENV['DATABASE_URL'] %>
